# Generated by Django 3.1.1 on 2021-01-16 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=3)),
                ('blood_group', models.CharField(max_length=5)),
                ('weight', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=15)),
                ('mobile2', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('disease', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
