# Generated by Django 3.1.1 on 2021-01-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
