# Generated by Django 3.1.1 on 2021-02-22 16:48

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dp',
            field=models.ImageField(blank=True, default='profile/default.png', null=True, upload_to=users.models.photo_path),
        ),
    ]
