# Generated by Django 3.1.1 on 2021-02-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='managed',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
