# Generated by Django 3.1.1 on 2021-02-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210223_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='managed',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
