# Generated by Django 3.1.1 on 2021-02-22 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20210223_0317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
