# Generated by Django 3.1.1 on 2021-03-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20210224_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='managed',
            field=models.CharField(blank=True, default='No', max_length=5),
        ),
    ]
